export enum PermissionType {
    EDIT_WORKFLOW = 'EDIT_WORKFLOW',
    DELETE_REQUEST = 'DELETE_REQUEST',
    APPROVE_CIVILIAN = 'APPROVE_CIVILIAN',
    APPROVE_SOLDIER = 'APPROVE_SOLDIER',
    APPROVE_CAR = 'APPROVE_CAR',
    EDIT_USER_PERMISSIONS = 'EDIT_USER_PERMISSIONS',
    EDIT_VISITOR_DETAILS = 'EDIT_VISITOR_DETAILS',
    VIEW_REQUESTS = 'VIEW_REQUESTS',
    CREATE_REQUESTS = 'CREATE_REQUESTS'
}

