export enum Permission {
    ADMIN = <any>'ADMIN',
    NORMAL_USER = <any>'NORMAL_USER',
    APPROVE_CIVILIAN = <any>'APPROVE_CIVILIAN',
    APPROVE_SOLDIER = <any>'APPROVE_SOLDIER',
    APPROVE_CAR = <any>'APPROVE_CAR',
    EDIT_USER_PERMISSIONS = <any>'EDIT_USER_PERMISSIONS'
}

